feat: index page publishing prepared (2)
geezers-io/Stock2U-front pull request #14
Opened 2023-10-16 16:46 UTC by Ellsy23

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-65](https://geezers-io.atlassian.net/browse/SU-65)

## What & Why

### _상품 목록 업데이트_
### _카드 컴포넌트 및 카드 목록 컴포넌트_

Mock 데이터를 사용하여 임시 업데이트 진행했습니다.

- 위치 정보 (latitude 및 longitude) 를 Coordinates(좌표) 로 통합했습니다.

### _인덱스 페이지 업데이트 및 상품 목록 컴포넌트 추가_

AI 추천 상품 및 마감 임박, 근처 상품:

- 'Heading' 태그의 'AI가 추천해주는 재고 매물' 폰트 사이즈를 lg 로 변경하고, 사용자에게 시각적으로 보이기 위해 홀로그램 색상을 입혔습니다.
- 상품 단락에 원화, 위치, 남은시간을 추가 업데이트 했습니다.

![image](https://github.com/geezers-io/Stock2U-front/assets/105610041/e543bb14-4229-443d-a289-a054a920c92e)

## Checklist
- [x] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-10-16 17:32 UTC, bear-bear-bear requested changes

2023-10-16 17:32 UTC, bear-bear-bear commented on src/pages/page.tsx
> +          }}
[변경 요청]
텍스트 예쁘네요 ~ 아래 변경사항만 반영해주세요.
1. {' '} 빼주세요.
2. text gradient 는 [chakra-ui 문서에 예제](https://chakra-ui.com/docs/styled-system/gradient#text-gradient-api)가 있습니다.
3. chakra-ui 에서 span 을 쓰고 싶다면 <Text as="span" ... /> 처럼 쓰면 됩니다.

2023-10-16 17:32 UTC, bear-bear-bear commented on src/pages/page.tsx
> +              solid"
[변경 요청]
?

2023-10-16 17:32 UTC, bear-bear-bear commented on src/pages/page.tsx
> +        coordinates={{ longitude: 1, latitude: 1 }} // 이 부분을 수정
[변경 요청]
이 두 속성은 각각의 product 가 가진 속성입니다. products 가 아니라요.

2023-10-17 15:06 UTC, Ash8382 commented on src/pages/page.tsx
> +          }}
변경 완료

2023-10-17 15:07 UTC, Ellsy23 commented on src/pages/page.tsx
> +              solid"
사소한 문제

2023-10-17 15:07 UTC, Ellsy23 commented on src/pages/page.tsx
> +        coordinates={{ longitude: 1, latitude: 1 }} // 이 부분을 수정
완료

2023-10-18 15:10 UTC, bear-bear-bear approved these changes

2023-10-18 15:22 UTC, heejung0413 commented
굿 ㅠㅠ 봤음 css 많이 고쳤네

2023-10-18 15:29 UTC, merged