feat: Main page API integration
geezers-io/Stock2U-front pull request #32
Opened 2023-11-02 13:46 UTC by Ellsy23

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-65](https://geezers-io.atlassian.net/browse/SU-65)

## What & Why

Index 페이지는 메인 화면을 표시하며, API와의 연동이 주된 목적입니다.

- 메인 페이지에서 필요한 데이터를 비동기적으로 가져오는 데 사용됩니다. 성공적으로 데이터를 가져오면 메인 페이지에서 해당 데이터를 활용하여 사용자에게 보여줄 수 있게 됩니다.

fetchDataFromAPI 함수는 메인 페이지에서 필요한 데이터를 가져오는 데 사용합니다. 

- ProductsService.getMainPageList를 호출하여 API로부터 데이터를 가져옵니다.

- pick 함수를 사용하여 geoLocation에서 필요한 데이터만 추출하여 API 요청에 전달합니다.

- API 요청이 성공하면 반환된 데이터를 setProducts를 통해 상태에 설정하여 페이지에서 사용할 수 있도록 합니다.

## Checklist
- [x] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-11-02 13:48 UTC, galaxy4276 commented on src/pages/page.tsx
>          'https://dthezntil550i.cloudfront.net/25/latest/252001022015123200005691112/1280_960/68ee10fa-84b8-44b6-bcc2-94df2f5fac05.png',
[의견]
요거 필요한 값인가요?

2023-11-02 13:49 UTC, galaxy4276 commented on src/pages/page.tsx
>          'https://dthezntil550i.cloudfront.net/25/latest/252001022015123200005691112/1280_960/68ee10fa-84b8-44b6-bcc2-94df2f5fac05.png',
아 귀칼배너엿네요

2023-11-02 13:49 UTC, galaxy4276 submitted a review, later dismissed

2023-11-02 13:50 UTC, galaxy4276 commented
타입 에러났어요

2023-11-02 14:17 UTC, bear-bear-bear approved these changes, later dismissed

2023-11-02 16:29 UTC, galaxy4276 approved these changes, later dismissed

2023-11-03 14:20 UTC, heejung0413 commented
잘했다~!

2023-11-03 15:48 UTC, bear-bear-bear requested changes
[변경 요청]
아직 ... 으로 되어있는 부분들 해결해주시고, 필터와 함께 이동해야 할 부분은 적용해주세요

2023-11-06 12:12 UTC, Ellsy23 commented
> [변경 요청] 아직 ... 으로 되어있는 부분들 해결해주시고, 필터와 함께 이동해야 할 부분은 적용해주세요

완

2023-11-10 16:11 UTC, bear-bear-bear approved these changes, later dismissed

2023-11-10 16:19 UTC, bear-bear-bear approved these changes

2023-11-10 16:19 UTC, merged