[재고 상세 페이지] 예약 API
geezers-io/Stock2U-front pull request #36
Opened 2023-11-08 13:49 UTC by heejung0413

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-135](https://geezers-io.atlassian.net/browse/SU-135)

## What & Why
- 예약 API 타입, axios로 호출 함수 작성
-  예약 요청 전송 가능 
- (( 예약 요청 취소 전송은 아직 구현 안됨 )) 

## Checklist
- [x ] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-11-08 14:56 UTC, will-kim-querypie requested changes

2023-11-08 14:56 UTC, bear-bear-bear commented on src/api/@types/Reservation.ts
> +}
👍👍🏻👍🏼👍🏽👍🏾👍🏿

2023-11-08 14:56 UTC, will-kim-querypie commented on src/api/@types/Reservation.ts
> +}
[변경 요청]
shared 에 이미 선언되어 있는 페이지네이션 타입을 활용해주세요

2023-11-08 14:56 UTC, will-kim-querypie commented on src/api/@types/Reservation.ts
> +  size: number;
[변경 요청]
shared 에 이미 선언되어 있는 페이지네이션 타입을 활용해주세요

2023-11-08 14:56 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +        <Grid p="1.2rem 0" onClick={onReserve({ productId })}>
[변경 요청]
타입에러 수정해주세요

2023-11-08 14:56 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +const ReservationButton = ({ productId }) => {
[변경 요청]
productId 가 any 타입으로 보입니다. 타이핑해주세요

2023-11-09 14:28 UTC, heejung0413 commented on src/api/@types/Reservation.ts
> +}
헷  ><

2023-11-09 14:29 UTC, heejung0413 commented on src/api/@types/Reservation.ts
> +}
오 안알려줘 아무도....

2023-11-10 13:34 UTC, bear-bear-bear approved these changes

2023-11-10 17:52 UTC, bear-bear-bear requested changes

2023-11-10 17:52 UTC, bear-bear-bear commented on src/api/@types/Reservation.ts
> +}
[변경 요청]
pageRequest extends 해주세요

2023-11-10 17:53 UTC, bear-bear-bear requested changes

2023-11-10 17:53 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +      console.log(id);
[변경 요청]
log 지워주세요

2023-11-10 17:53 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +      if (!id) return;
[질문]
이게 falsy 일 수가 있나요?

2023-11-10 17:53 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +      toast.error('에약 취소 요청 전송에 실패했어요.');
[의견]
전송 이란 단어 붙일지 말지 하나만 하는게 좋을듯 합니다

2023-11-13 12:47 UTC, galaxy4276 approved these changes, later dismissed

2023-11-13 12:47 UTC, galaxy4276 commented on src/components/domains/products/ReservationButton.tsx
[의견]
해당 코드 정리바람

2023-11-13 12:47 UTC, galaxy4276 commented on src/components/domains/products/ReservationButton.tsx
> +      console.log({ id });
[의견]
해당 코드 정리바람

2023-11-13 12:55 UTC, heejung0413 commented on src/components/domains/products/ReservationButton.tsx
보고~

2023-11-13 13:04 UTC, galaxy4276 requested changes

2023-11-13 13:04 UTC, galaxy4276 commented on src/components/domains/products/ReservationButton.tsx
>    };
```suggestion
  const onReserve = async () => {
    try {
      const { id } = await ReservationService.create(productId);
      setReservation({
        id,
        status: ReservationStatus.REQUESTED,
      });
      toast.success('예약 요청에 성공했어요!');
    } catch (error: any) {
      if (error.response && error.response.status === 410) {
        toast.info('이미 예약이 요청되어 있습니다. 판매자 측에서 처리될 때까지 기다려주세요');
      } else {
        toast.error('에약 요청에 실패했어요');
      }
    }
  };
```

productId 는 동적인 값이 아니기때문에 인자로 받지 않아도 될 것같아요.

2023-11-13 13:06 UTC, bear-bear-bear requested changes

2023-11-13 13:06 UTC, bear-bear-bear commented on src/components/domains/products/ImageViewer.tsx
> +          h={{ base: 'auto', [HORIZONTAL_POINT]: '25vh' }}
[변경 요청]
앱 width 는 고정되어있기 때문에 스크린 높이가 높아지면 비율이 굉장히 이상해질겁니다

2023-11-13 13:06 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +  reservationStatus: ReservationStatus | undefined;
[의견]
축약할 수 있습니다
reservationStatus?: ReservationStatus;

2023-11-13 13:06 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +  const canRequestReservation = !reservation.id;
[의견]
canReservation 으로 줄여도 될 것 같아요

2023-11-13 13:06 UTC, bear-bear-bear commented on src/components/domains/products/ReservationButton.tsx
> +      }
[의견]
error 는 AxiosError 타입입니다.

``` ts
    } catch (e) {
      const error = e as AxiosError;
      if (error.response && error.response.status === 410) {
        toast.info('이미 예약이 요청되어 있습니다. 판매자 측에서 처리될 때까지 기다려주세요');
      } else {
        toast.error('에약 요청에 실패했어요');
      }
```

2023-11-13 15:34 UTC, galaxy4276 approved these changes
고생하셨어요.

2023-11-13 15:50 UTC, bear-bear-bear approved these changes

2023-11-13 16:18 UTC, merged