feat: [메인 페이지] 상품 등록 페이지로 이동하는 버튼 구현
geezers-io/Stock2U-front pull request #40
Opened 2023-11-15 09:15 UTC by heejung0413

## Type
- [x] Feature
- [ ] Fix

## What & Why

- **판매자에게만 메인페이지에 상품등록 페이지로 이동하는 버튼**이 보입니다.
- **postion:sticky**

## Checklist
- [ ] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-11-15 09:19 UTC, galaxy4276 commented on src/pages/page.tsx
> +  if (!user) return;
[의견]
!user || user.role !== UserRole.Seller 인 경우가 좀 더 불필요한 렌더링을 방지할 수 있겠다는 생각이 듭니다.
물론 현재도 화면상 이슈는 발생하지 않을 듯 해요.

2023-11-15 09:19 UTC, galaxy4276 commented on src/pages/page.tsx
> +const ButtonStyle = styled.div`
[의견]
ButtonStyle 은 버튼 컴포넌트를 의미하기 어려운 이름인 것 같습니다.
`Button 을 위한 Properties 로 추측됨`

2023-11-15 10:46 UTC, galaxy4276 submitted a review, later dismissed

2023-11-15 16:06 UTC, bear-bear-bear requested changes

2023-11-15 16:06 UTC, bear-bear-bear commented on src/pages/page.tsx
> +  if (!user) return;
[변경 요청]
기획상 로그인을 안했더라도 상품 열람은 가능합니다.

2023-11-15 16:06 UTC, bear-bear-bear commented on src/pages/page.tsx
> +  background: royalblue;
[변경요청]
정의되지 않은 컬러입니다.
emotion 에서 theme 을 사용하는 방법을 찾아보세요

2023-11-15 16:06 UTC, bear-bear-bear commented on src/pages/page.tsx
> +
[변경요청]
1. sticky 보단 fixed 가 용도에 맞는듯 합니다.
2. position 속성은 내부 요소가 아닌 Link 에 매겨져야 할 듯 합니다.
3. emotion 으로 만들지말고 그냥 Button 가져다 쓰고, [role="presentation"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role) 주는게 좋을 듯 합니다.

2023-11-16 14:50 UTC, bear-bear-bear approved these changes

2023-11-16 14:58 UTC, merged