feat: 상품상세페이지 mock데이터 생성, 퍼블리싱 기반작업
geezers-io/Stock2U-front pull request #8
Opened 2023-10-14 14:12 UTC by heejung0413

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-70](https://geezers-io.atlassian.net/browse/SU-70)

## What & Why

상품 상세페이지에 들어갈 데이터를 임시로 생성하였고, 
퍼블리싱 기반 작업을 위한 tsx 파일 생성 및 라우터 형성 작업을 하였습니다.

## Checklist
- [x] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-10-14 14:14 UTC, galaxy4276 commented on src/api/__mock__/product.ts
> +};
[의견]
실제데이터는 이러한 구조와 많이 다를거에요.
담당자분과 한 번 논의해보시는걸 권해드려요.

2023-10-14 14:17 UTC, bear-bear-bear requested changes

2023-10-14 14:17 UTC, bear-bear-bear commented on src/App.tsx
> +    element: <AuthLayout />,
[변경 요청]
AuthLayout 아닌듯

2023-10-14 14:17 UTC, bear-bear-bear commented on src/api/__mock__/product.ts
> +  subImageUrls: ['https://~~', 'https://~~'],
[의견]
실제 이미지 URL 이 들어가야 컴포넌트 개발 시 유용할 듯 함다

2023-10-14 14:17 UTC, bear-bear-bear commented on src/pages/product/[id]/page.tsx
> +  }
[의견]
<img width="812" alt="image" src="https://github.com/geezers-io/Stock2U-front/assets/57123802/93301d0a-1c63-4ecc-ac6d-402473475c85">

2023-10-14 14:18 UTC, heejung0413 commented on src/api/__mock__/product.ts
> +  subImageUrls: ['https://~~', 'https://~~'],
넵

2023-10-14 14:34 UTC, heejung0413 commented on src/api/__mock__/product.ts
> +};
넵 담당자님 연락해서 원활한 합의(?)가 이루어지면 그때 바꾸도록 하겠습니다.
일단 퍼블리싱 작업을 먼저 하려 합니다!

2023-10-15 17:18 UTC, heejung0413 reviewed
페이지 css 윤곽은 어느 정도 잡았습니다.. <ImageSelector/> 컴포넌트는 작성 중입니다.

2023-10-15 18:07 UTC, bear-bear-bear requested changes

2023-10-15 18:07 UTC, bear-bear-bear commented on src/pages/product/[id]/page.tsx
> +`;
[변경 요청]
chakra-ui 컴포넌트들을 사용할 수 있을 것 같아요

2023-10-15 18:07 UTC, bear-bear-bear commented on src/pages/product/[id]/page.tsx
> +            상세 내용
[질문]
{' '} 들은 왜 들어가있나요?

2023-10-15 18:07 UTC, bear-bear-bear commented on src/components/domains/product/ImageSelector.tsx
> +import ImageGallery from 'react-image-gallery';
[변경요청]
라이브러리 쓰지 말고 직접 만들어주세요. 라이브러리 쓸 정도로 복잡한 로직이 아닙니다.

2023-10-16 12:23 UTC, bear-bear-bear commented on src/App.tsx
> +  },
[의견]
#12 PR 에선 products 인데 여긴 product 네요, 머지 때 products 로 변경하는게 좋을 것 같아요

2023-10-16 12:23 UTC, bear-bear-bear commented on src/components/domains/product/ImageSelector.tsx
> +    <Box w="100%" h="100%" display="flex" justifyContent="center" alignItems="center" bgColor={colors.brand[100]}>
[변경 요청]
bgColor="brand.100" 하시면 됩니다

2023-10-16 13:00 UTC, heejung0413 commented on src/App.tsx
> +  },
넵 ㅠ 피그마 보니 product와 products 둘 다 있길래 다른 건 줄 알았습니다 ㅠㅠ 바꾸겠습니다

2023-10-26 16:39 UTC, bear-bear-bear approved these changes, later dismissed

2023-10-26 16:58 UTC, bear-bear-bear approved these changes, later dismissed

2023-10-26 17:10 UTC, bear-bear-bear approved these changes

2023-10-27 14:34 UTC, merged